### ISSUE TITLE
Add a play button for cells

### ISSUE THREAD

**Issue by eliascarv** [jtpio/jupyterlab-classic#103]
On the Jupyter Notebook, we have a play button to execute the code in a simple way. This is also very useful for those who use Jupyter on smartphones. Can you add this feature to Jupyterlab-Classic?
PS. Sorry for my English, I'm Brazilian.

![Screenshot_20210216-145528_Samsung Internet](https://user-images.githubusercontent.com/73039601/108103382-a14cb280-7068-11eb-95a0-3a6d44c58548.jpg)

![Screenshot_20210216-150700_Samsung Internet](https://user-images.githubusercontent.com/73039601/108103386-a27ddf80-7068-11eb-8610-7d2059762fe6.jpg)

**Comment by jtpio** [comment]
Thanks @eliascarv for the suggestion!

As a start, it might be possible to install the `jlab-enhanced-cell-toolbar` extension for JupyterLab, which should also work in JupyterLab Classic. It can be installed with `pip install jlab-enhanced-cell-toolbar`.

It will add the run button next to the input cell:

![image](https://user-images.githubusercontent.com/591645/108179835-5b462c00-7106-11eb-81a1-676349097a4b.png)

More info in the repo: https://github.com/jupyterlab-contrib/jlab-enhanced-cell-toolbar

**Comment by jtpio** [comment]
OK so it looks like this extension unfortunately doesn't work out of the box with JupyterLab Classic.

This seems to be related to `@jupyterlab/celltags` not being exposed by JupyterLab Classic, while `jlab-enhanced-cell-toolbar` expects to find it since it has been compiled against JupyterLab, and `@jupyterlab/celltags` ends up in the webpack shared scope.

![image](https://user-images.githubusercontent.com/591645/109189961-e40f3880-7794-11eb-9043-81592c8f2718.png)

In some way this makes sense, since `@jupyterlab/celltags` is provided by JupyterLab via the `celltags-extension`. But in JupyterLab Classic `celltags-extension` is not part of the build.

**Comment by jtpio** [comment]
@eliascarv the short story is that it should be possible to fix this in JupyterLab Classic, so the extension can be installed and work out of the box.

**Comment by thoth291** [comment]
The play button in `jlab` is visually misaligned to the start of the cell.
Moreover, it should be visible even if cell is not active.
And, in addition to that, when the cell is hidden using `hide_code` - the play button should be there and next to the cell.
Current version of that extension is not usable/comparable.

**Comment by jtpio** [comment]
@eliascarv normally with #106 it should be possible to install the `jlab-enhanced-cell-toolbar` extension and have the extra cell buttons including the run button.

But feel free to reopen if you think this should be part of JupyterLab Classic by default. Thanks!
